[package]
name = "hexlab"
version = "0.1.0"
edition = "2021"
description = "A hexagonal maze library"
license = "MIT OR Apache-2.0"

[dependencies]
hexx = { version = "0.18" }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde", "hexx/serde"]

[dev-dependencies]
serde_json = "1.0"
